---
experiment:
 time: 60
 output_directory: './results/'
network:
 server1:
  ip: '10.50.0.2'
  int: 'vns_recv'
  traffic:
   server:
     use_pfring: 'True'
     enabled: 'True'
     disable_output: 'True'
     disable_time_corrector: 'False'
     ports: [0]
     length: 1500
 client1:
  ip: '10.50.0.1'
  int: 'vns_send'
  traffic:
   client:
     distribution: 'max'
     intensity: 500000
     npackets: 0
     length: 1500
     direction: '10.50.0.2'
     direction_mac: '02:00:00:00:00:02'
     port: 0
     use_pfring: 'True'
     single_thread: 'True'
     disable_output: 'True'
     disable_timestamps: 'False'
     measure_latency: 'False'
     sync_time: 0
   server:
     enabled: 'False'
